def svg2png(
    bytestring: bytes | None = None,
    *,
    file_obj: object | None = None,
    url: str | None = None,
    dpi: int = 96,
    parent_width: int | None = None,
    parent_height: int | None = None,
    scale: int = 1,
    unsafe: bool = False,
    background_color: str | None = None,
    negate_colors: bool = False,
    invert_images: bool = False,
    write_to: str | object | None = None,
    output_width: int | None = None,
    output_height: int | None = None,
) -> bytes | None: ...
def svg2pdf(
    bytestring: bytes | None = None,
    *,
    file_obj: object | None = None,
    url: str | None = None,
    dpi: int = 96,
    parent_width: int | None = None,
    parent_height: int | None = None,
    scale: int = 1,
    unsafe: bool = False,
    background_color: str | None = None,
    negate_colors: bool = False,
    invert_images: bool = False,
    write_to: str | object | None = None,
    output_width: int | None = None,
    output_height: int | None = None,
) -> bytes | None: ...
