# Type stub for cairo
from typing import Any

class Context:
    def __init__(self, target: Any) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def stroke(self) -> None: ...
    def set_source_rgb(self, r: float, g: float, b: float) -> None: ...

class Surface:
    def __init__(self, width: int, height: int) -> None: ...
    def write_to_png(self, filename: str) -> None: ...

def ImageSurface(format: int, width: int, height: int) -> Surface: ...

FORMAT_ARGB32: int
FORMAT_RGB24: int
